# Generated by Django 5.2.5 on 2025-08-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='chat_type',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='group', max_length=10),
        ),
    ]
