# Generated by Django 5.2.5 on 2025-08-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_chat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='chat_type',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=10),
        ),
    ]
