# Generated by Django 5.2.5 on 2025-09-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='chat/'),
        ),
    ]
